name: Deploy to Production

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          port: 22
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            cd ${{ secrets.PROD_PATH }}
            git pull origin develop
            docker-compose up -d --build
            docker system prune -a -f --filter "until=24h"
